[package]
name = "bridge_of_bridges"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
distributed_bridge = { path = "network" }
spdlog_bridge = { path = "spdlog" }
